export const USER_REMOVED = "USER_REMOVED";
export const USER_EDIT = "USER_EDIT";
export const USER_CREATE = "USER_CREATE";
export const ALL_USERS = "ALL_USERS";

export const FETCH_USER_START = "FETCH_USER_START";
export const FETCH_USER_SUCCESS = "FETCH_USER_SUCCESS";
export const FETCH_USER_FAIL = "FETCH_USER_FAIL";


export const PRODUCT_REMOVED = "PRODUCT_REMOVED";
export const PRODUCT_EDIT = "PRODUCT_EDIT";
export const PRODUCT_CREATE = "PRODUCT_CREATE";
export const ALL_PRODUCTS = "ALL_PRODUCTS";

export const FETCH_PRODUCT_START = "FETCH_PRODUCT_START";
export const FETCH_PRODUCT_SUCCESS = "FETCH_PRODUCT_SUCCESS";
export const FETCH_PRODUCT_FAIL = "FETCH_PRODUCT_FAIL";


export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_LOGOUT = "AUTH_LOGOUT";